# Bật dòng này khi bạn code ở máy Local (Spring Boot sẽ tự đọc file application-dev)
spring.profiles.active=dev

# (Khi nào muốn máy Local kết nối thẳng lên Azure SQL trực tuyến để kiểm tra dữ liệu, bạn chỉ cần sửa chữ 'dev' thành 'prod')
# spring.profiles.active=prod

spring.application.name=seal-hackathon-backend
server.port=8080

# === Cấu hình Bảo mật chung ===
app.jwt.secret=VGhpc0lzQVN0cm9uZzI1NkJpdEJhc2U2NFNlY3JldEtleUZvclN3cDM5MQ==
app.jwt.expiration-seconds=3600
app.auth.auto-approve-new-user=false

# === Cấu hình JPA / Hibernate chung ===
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
