# === KẾT NỐI DATABASE AWS RDS MS SQL ONLINE ===
# Đảm bảo dùng dấu hai chấm :1433 để cố định cổng kết nối của AWS [đã thảo luận trước đó]
spring.datasource.url=jdbc:sqlserver://${DB_HOST}:1433;databaseName=${DB_NAME};encrypt=true;trustServerCertificate=true;loginTimeout=30;
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# === Cấu hình cố định cho Đám mây ===
spring.jpa.hibernate.ddl-auto=none